---
- name: "Upgrading packages"
  become: true
  apt:
    upgrade: yes

- name: "Installing NodeJS and NPM"
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "Installing pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present